In [2]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [3]:
### Load the dataset
data = pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
## drop unwanted columns

data=data.drop(['RowNumber',	'CustomerId',	'Surname'],axis=1)

In [5]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [6]:
## encode categorical variables
label=LabelEncoder()
data['Gender']=label.fit_transform(data['Gender'])

In [7]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [8]:
## we use One hot encoder
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()

In [9]:
encoded_data=encoder.fit_transform(data[['Geography']])

In [10]:
encoded_data.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [11]:
encoder.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [12]:
encoded_data=pd.DataFrame(encoded_data.toarray(),columns=encoder.get_feature_names_out(['Geography']))

In [13]:
encoded_data

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [14]:
data=pd.concat([data.drop('Geography',axis=True),encoded_data],axis=1)

In [15]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [16]:
with open('label_encoder.pkl','wb') as file:
    pickle.dump(label,file)

In [17]:
with open('oneHot_encoder.pkl','wb') as file:
    pickle.dump(encoder,file)

In [18]:
## Divide the independent and dependent features
x= data.drop('Exited',axis=1)
y=data['Exited']

In [19]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [20]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [21]:
x_train.shape

(8000, 12)

In [22]:
x_test.shape

(2000, 12)

In [23]:
x_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [24]:
x_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(2000, 12))

In [25]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [28]:
#### ANN implementation 
import tensorflow as tf
from tenserflow.keras.models import Sequential
from tenserflow.keras.layers import dense
from tenserflow.keras.callbacks import EarlyStopping,TenserBoard
import datetime

ModuleNotFoundError: No module named 'tenserflow'

In [27]:
%pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorflow) (25.0)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorflow) (6.33.0)
Requirement already satisfied: requests<3,>=2.21.0 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorflow) (2.1.1)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.78.0-cp313-cp313-win_amd64.whl.metadata (3.9 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.13.2-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorflow) (2.3.3)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp313-cp313-win_amd64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.10.5)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.46.3-py3-none-any.whl.metadata (2.4 kB)
Collecting rich (from keras>=3.12.0->tensorflow)
  Downloading rich-14.3.3-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.12.0->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Downloading optree-0.19.0-cp313-cp313-win_amd64.whl.metadata (35 kB)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.12.0->tensorflow)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.3/351.2 MB ? eta -:--:--
   ---------------------------------------- 0.8/351.2 MB 1.3 MB/s eta 0:04:22
   ---------------------------------------- 1.0/351.2 MB 1.5 MB/s eta 0:03:57
   ---------------------------------------- 1.6/351.2 MB 1.6 MB/s eta 0:03:37
   ---------------------------------------- 2.1/351.2 MB 1.8 MB/s eta 0:03:19
   ---------------------------------------- 2.6/351.2 MB 1.9 MB/s eta 0:03:01
   ---------------------------------------- 3.1/351.2 MB 2.1 MB/s eta 0:02:48
   ---------------------------------------- 3.9/351.2 MB 2.3 MB/s eta 0:02:33
    --------------------------------------- 5.0/351.2 MB 2.5 MB/s eta 0:02:18
    --------------------------------------- 5.8/351.2 MB 2.7 MB/s eta 0:02:09
    --------------------------------------- 6.8/351.2 MB 2.9 MB/s eta 0:02:01
    --------------------------------------- 7.9/351.2 MB 3.1 MB/s eta 0:01:53
    --------------------------------------- 8.7/351.2 MB 3.1 MB/s eta 0:01:49
   - -------------------------------------- 10.0/351.2 MB 3.3 MB/s eta 0:01:43
   - -------------------------------------- 11.3/351.2 MB 3.5 MB/s eta 0:01:38
   - -------------------------------------- 12.3/351.2 MB 3.6 MB/s eta 0:01:34
   - -------------------------------------- 13.6/351.2 MB 3.8 MB/s eta 0:01:30
   - -------------------------------------- 14.9/351.2 MB 3.9 MB/s eta 0:01:27
   - -------------------------------------- 16.3/351.2 MB 4.0 MB/s eta 0:01:25
   - -------------------------------------- 17.0/351.2 MB 4.0 MB/s eta 0:01:24
   -- ------------------------------------- 18.4/351.2 MB 4.1 MB/s eta 0:01:22
   -- ------------------------------------- 19.7/351.2 MB 4.2 MB/s eta 0:01:20
   -- ------------------------------------- 20.7/351.2 MB 4.2 MB/s eta 0:01:19
   -- ------------------------------------- 22.0/351.2 MB 4.3 MB/s eta 0:01:17
   -- ------------------------------------- 23.3/351.2 MB 4.4 MB/s eta 0:01:15
   -- ------------------------------------- 24.6/351.2 MB 4.5 MB/s eta 0:01:14
   -- ------------------------------------- 25.7/351.2 MB 4.4 MB/s eta 0:01:14
   --- ------------------------------------ 26.7/351.2 MB 4.5 MB/s eta 0:01:13
   --- ------------------------------------ 28.0/351.2 MB 4.6 MB/s eta 0:01:11
   --- ------------------------------------ 29.4/351.2 MB 4.6 MB/s eta 0:01:11
   --- ------------------------------------ 30.7/351.2 MB 4.6 MB/s eta 0:01:10
   --- ------------------------------------ 32.0/351.2 MB 4.7 MB/s eta 0:01:09
   --- ------------------------------------ 33.3/351.2 MB 4.7 MB/s eta 0:01:08
   --- ------------------------------------ 34.6/351.2 MB 4.8 MB/s eta 0:01:07
   ---- ----------------------------------- 35.9/351.2 MB 4.8 MB/s eta 0:01:06
   ---- ----------------------------------- 37.0/351.2 MB 4.8 MB/s eta 0:01:06
   ---- ----------------------------------- 38.0/351.2 MB 4.8 MB/s eta 0:01:06
   ---- ----------------------------------- 39.6/351.2 MB 4.9 MB/s eta 0:01:05
   ---- ----------------------------------- 40.4/351.2 MB 4.8 MB/s eta 0:01:05
   ---- ----------------------------------- 41.7/351.2 MB 4.9 MB/s eta 0:01:04
   ---- ----------------------------------- 42.7/351.2 MB 4.9 MB/s eta 0:01:04
   ----- ---------------------------------- 44.0/351.2 MB 4.9 MB/s eta 0:01:03
   ----- ---------------------------------- 45.4/351.2 MB 4.9 MB/s eta 0:01:03
   ----- ---------------------------------- 46.1/351.2 MB 4.9 MB/s eta 0:01:03
   ----- ---------------------------------- 47.4/351.2 MB 4.9 MB/s eta 0:01:02
   ----- ---------------------------------- 48.8/351.2 MB 5.0 MB/s eta 0:01:02
   ----- ---------------------------------- 50.1/351.2 MB 5.0 MB/s eta 0:01:01
   ----- ---------------------------------- 51.4/351.2 MB 5.0 MB/s eta 0:01:00
   ------ --------------------------------- 52.7/351.2 MB 5.0 MB/s eta 0:01:00
   ------ --------------------------------- 54.0/351.2 MB 5.0 MB/s eta 0:00:59
   ------ --------------------------------- 55.1/351.2 MB 5.1 MB/s eta 0:00:59
   ------ --------------------------------- 56.4/351.2 MB 5.1 MB/s eta 0:00:59
   ------ --------------------------------- 57.7/351.2 MB 5.1 MB/s eta 0:00:58
   ------ --------------------------------- 58.7/351.2 MB 5.1 MB/s eta 0:00:58
   ------ --------------------------------- 59.8/351.2 MB 5.1 MB/s eta 0:00:58
   ------ --------------------------------- 61.1/351.2 MB 5.1 MB/s eta 0:00:57
   ------- -------------------------------- 62.1/351.2 MB 5.1 MB/s eta 0:00:57
   ------- -------------------------------- 63.4/351.2 MB 5.1 MB/s eta 0:00:57
   ------- -------------------------------- 64.7/351.2 MB 5.1 MB/s eta 0:00:56
   ------- -------------------------------- 65.8/351.2 MB 5.1 MB/s eta 0:00:56
   ------- -------------------------------- 67.1/351.2 MB 5.1 MB/s eta 0:00:56
   ------- -------------------------------- 68.4/351.2 MB 5.2 MB/s eta 0:00:55
   ------- -------------------------------- 69.5/351.2 MB 5.2 MB/s eta 0:00:55
   -------- ------------------------------- 70.5/351.2 MB 5.2 MB/s eta 0:00:55
   -------- ------------------------------- 71.8/351.2 MB 5.2 MB/s eta 0:00:55
   -------- ------------------------------- 73.1/351.2 MB 5.2 MB/s eta 0:00:54
   -------- ------------------------------- 74.4/351.2 MB 5.2 MB/s eta 0:00:54
   -------- ------------------------------- 75.5/351.2 MB 5.2 MB/s eta 0:00:54
   -------- ------------------------------- 76.8/351.2 MB 5.2 MB/s eta 0:00:53
   -------- ------------------------------- 77.6/351.2 MB 5.2 MB/s eta 0:00:53
   -------- ------------------------------- 78.1/351.2 MB 5.2 MB/s eta 0:00:53
   --------- ------------------------------ 79.4/351.2 MB 5.2 MB/s eta 0:00:53
   --------- ------------------------------ 79.7/351.2 MB 5.2 MB/s eta 0:00:53
   --------- ------------------------------ 81.5/351.2 MB 5.1 MB/s eta 0:00:53
   --------- ------------------------------ 82.8/351.2 MB 5.2 MB/s eta 0:00:53
   --------- ------------------------------ 83.9/351.2 MB 5.2 MB/s eta 0:00:52
   --------- ------------------------------ 85.2/351.2 MB 5.2 MB/s eta 0:00:52
   --------- ------------------------------ 86.5/351.2 MB 5.2 MB/s eta 0:00:52
   --------- ------------------------------ 87.6/351.2 MB 5.2 MB/s eta 0:00:51
   ---------- ----------------------------- 88.9/351.2 MB 5.2 MB/s eta 0:00:51
   ---------- ----------------------------- 89.9/351.2 MB 5.2 MB/s eta 0:00:51
   ---------- ----------------------------- 91.2/351.2 MB 5.2 MB/s eta 0:00:50
   ---------- ----------------------------- 92.3/351.2 MB 5.2 MB/s eta 0:00:50
   ---------- ----------------------------- 93.6/351.2 MB 5.2 MB/s eta 0:00:50
   ---------- ----------------------------- 94.9/351.2 MB 5.2 MB/s eta 0:00:50
   ---------- ----------------------------- 96.2/351.2 MB 5.2 MB/s eta 0:00:49
   ----------- ---------------------------- 97.3/351.2 MB 5.2 MB/s eta 0:00:49
   ----------- ---------------------------- 98.3/351.2 MB 5.2 MB/s eta 0:00:49
   ----------- ---------------------------- 99.4/351.2 MB 5.2 MB/s eta 0:00:49
   ----------- ---------------------------- 100.7/351.2 MB 5.2 MB/s eta 0:00:48
   ----------- ---------------------------- 102.0/351.2 MB 5.2 MB/s eta 0:00:48
   ----------- ---------------------------- 103.3/351.2 MB 5.3 MB/s eta 0:00:48
   ----------- ---------------------------- 104.6/351.2 MB 5.3 MB/s eta 0:00:47
   ------------ --------------------------- 105.9/351.2 MB 5.3 MB/s eta 0:00:47
   ------------ --------------------------- 107.0/351.2 MB 5.3 MB/s eta 0:00:47
   ------------ --------------------------- 108.3/351.2 MB 5.3 MB/s eta 0:00:46
   ------------ --------------------------- 109.6/351.2 MB 5.3 MB/s eta 0:00:46
   ------------ --------------------------- 110.9/351.2 MB 5.3 MB/s eta 0:00:46
   ------------ --------------------------- 112.2/351.2 MB 5.3 MB/s eta 0:00:45
   ------------ --------------------------- 113.5/351.2 MB 5.3 MB/s eta 0:00:45
   ------------- -------------------------- 114.8/351.2 MB 5.3 MB/s eta 0:00:45
   ------------- -------------------------- 115.9/351.2 MB 5.3 MB/s eta 0:00:45
   ------------- -------------------------- 117.2/351.2 MB 5.3 MB/s eta 0:00:44
   ------------- -------------------------- 117.7/351.2 MB 5.3 MB/s eta 0:00:44
   ------------- -------------------------- 119.0/351.2 MB 5.3 MB/s eta 0:00:44
   ------------- -------------------------- 120.1/351.2 MB 5.3 MB/s eta 0:00:44
   ------------- -------------------------- 121.4/351.2 MB 5.3 MB/s eta 0:00:44
   ------------- -------------------------- 122.7/351.2 MB 5.3 MB/s eta 0:00:43
   -------------- ------------------------- 124.0/351.2 MB 5.3 MB/s eta 0:00:43
   -------------- ------------------------- 125.3/351.2 MB 5.3 MB/s eta 0:00:43
   -------------- ------------------------- 126.4/351.2 MB 5.4 MB/s eta 0:00:43
   -------------- ------------------------- 127.4/351.2 MB 5.4 MB/s eta 0:00:42
   -------------- ------------------------- 128.5/351.2 MB 5.3 MB/s eta 0:00:42
   -------------- ------------------------- 129.8/351.2 MB 5.3 MB/s eta 0:00:42
   -------------- ------------------------- 131.1/351.2 MB 5.4 MB/s eta 0:00:42
   --------------- ------------------------ 132.4/351.2 MB 5.4 MB/s eta 0:00:41
   --------------- ------------------------ 133.4/351.2 MB 5.4 MB/s eta 0:00:41
   --------------- ------------------------ 134.5/351.2 MB 5.4 MB/s eta 0:00:41
   --------------- ------------------------ 135.8/351.2 MB 5.4 MB/s eta 0:00:41
   --------------- ------------------------ 137.4/351.2 MB 5.4 MB/s eta 0:00:40
   --------------- ------------------------ 138.4/351.2 MB 5.4 MB/s eta 0:00:40
   --------------- ------------------------ 139.7/351.2 MB 5.4 MB/s eta 0:00:40
   ---------------- ----------------------- 141.3/351.2 MB 5.4 MB/s eta 0:00:39
   ---------------- ----------------------- 142.6/351.2 MB 5.4 MB/s eta 0:00:39
   ---------------- ----------------------- 143.9/351.2 MB 5.4 MB/s eta 0:00:39
   ---------------- ----------------------- 144.7/351.2 MB 5.4 MB/s eta 0:00:39
   ---------------- ----------------------- 145.8/351.2 MB 5.4 MB/s eta 0:00:39
   ---------------- ----------------------- 147.1/351.2 MB 5.4 MB/s eta 0:00:38
   ---------------- ----------------------- 148.4/351.2 MB 5.4 MB/s eta 0:00:38
   ----------------- ---------------------- 149.4/351.2 MB 5.4 MB/s eta 0:00:38
   ----------------- ---------------------- 150.7/351.2 MB 5.4 MB/s eta 0:00:38
   ----------------- ---------------------- 152.0/351.2 MB 5.4 MB/s eta 0:00:37
   ----------------- ---------------------- 153.4/351.2 MB 5.4 MB/s eta 0:00:37
   ----------------- ---------------------- 154.7/351.2 MB 5.4 MB/s eta 0:00:37
   ----------------- ---------------------- 155.7/351.2 MB 5.4 MB/s eta 0:00:37
   ----------------- ---------------------- 157.0/351.2 MB 5.4 MB/s eta 0:00:36
   ------------------ --------------------- 158.3/351.2 MB 5.4 MB/s eta 0:00:36
   ------------------ --------------------- 159.6/351.2 MB 5.4 MB/s eta 0:00:36
   ------------------ --------------------- 161.0/351.2 MB 5.4 MB/s eta 0:00:36
   ------------------ --------------------- 162.3/351.2 MB 5.4 MB/s eta 0:00:35
   ------------------ --------------------- 163.6/351.2 MB 5.5 MB/s eta 0:00:35
   ------------------ --------------------- 164.9/351.2 MB 5.5 MB/s eta 0:00:34
   ------------------ --------------------- 166.2/351.2 MB 5.5 MB/s eta 0:00:34
   ------------------- -------------------- 167.5/351.2 MB 5.6 MB/s eta 0:00:34
   ------------------- -------------------- 168.6/351.2 MB 5.6 MB/s eta 0:00:33
   ------------------- -------------------- 169.9/351.2 MB 5.6 MB/s eta 0:00:33
   ------------------- -------------------- 171.2/351.2 MB 5.6 MB/s eta 0:00:33
   ------------------- -------------------- 172.5/351.2 MB 5.6 MB/s eta 0:00:32
   ------------------- -------------------- 173.8/351.2 MB 5.6 MB/s eta 0:00:32
   ------------------- -------------------- 175.1/351.2 MB 5.7 MB/s eta 0:00:32
   -------------------- ------------------- 176.4/351.2 MB 5.7 MB/s eta 0:00:31
   -------------------- ------------------- 177.7/351.2 MB 5.7 MB/s eta 0:00:31
   -------------------- ------------------- 179.0/351.2 MB 5.7 MB/s eta 0:00:31
   -------------------- ------------------- 180.4/351.2 MB 5.7 MB/s eta 0:00:30
   -------------------- ------------------- 181.7/351.2 MB 5.7 MB/s eta 0:00:30
   -------------------- ------------------- 183.0/351.2 MB 5.7 MB/s eta 0:00:30
   -------------------- ------------------- 184.0/351.2 MB 5.7 MB/s eta 0:00:30
   --------------------- ------------------ 185.1/351.2 MB 5.7 MB/s eta 0:00:30
   --------------------- ------------------ 186.4/351.2 MB 5.7 MB/s eta 0:00:29
   --------------------- ------------------ 187.7/351.2 MB 5.7 MB/s eta 0:00:29
   --------------------- ------------------ 189.0/351.2 MB 5.7 MB/s eta 0:00:29
   --------------------- ------------------ 190.3/351.2 MB 5.7 MB/s eta 0:00:29
   --------------------- ------------------ 191.6/351.2 MB 5.7 MB/s eta 0:00:28
   --------------------- ------------------ 192.9/351.2 MB 5.7 MB/s eta 0:00:28
   ---------------------- ----------------- 194.0/351.2 MB 5.7 MB/s eta 0:00:28
   ---------------------- ----------------- 195.6/351.2 MB 5.7 MB/s eta 0:00:28
   ---------------------- ----------------- 196.6/351.2 MB 5.7 MB/s eta 0:00:28
   ---------------------- ----------------- 197.9/351.2 MB 5.7 MB/s eta 0:00:27
   ---------------------- ----------------- 199.2/351.2 MB 5.7 MB/s eta 0:00:27
   ---------------------- ----------------- 200.5/351.2 MB 5.7 MB/s eta 0:00:27
   ---------------------- ----------------- 201.6/351.2 MB 5.7 MB/s eta 0:00:27
   ----------------------- ---------------- 203.2/351.2 MB 5.7 MB/s eta 0:00:26
   ----------------------- ---------------- 204.2/351.2 MB 5.7 MB/s eta 0:00:26
   ----------------------- ---------------- 205.5/351.2 MB 5.7 MB/s eta 0:00:26
   ----------------------- ---------------- 206.8/351.2 MB 5.7 MB/s eta 0:00:26
   ----------------------- ---------------- 208.1/351.2 MB 5.7 MB/s eta 0:00:26
   ----------------------- ---------------- 208.9/351.2 MB 5.7 MB/s eta 0:00:25
   ----------------------- ---------------- 210.2/351.2 MB 5.7 MB/s eta 0:00:25
   ------------------------ --------------- 211.6/351.2 MB 5.7 MB/s eta 0:00:25
   ------------------------ --------------- 212.9/351.2 MB 5.7 MB/s eta 0:00:25
   ------------------------ --------------- 214.2/351.2 MB 5.7 MB/s eta 0:00:24
   ------------------------ --------------- 215.2/351.2 MB 5.7 MB/s eta 0:00:24
   ------------------------ --------------- 216.5/351.2 MB 5.7 MB/s eta 0:00:24
   ------------------------ --------------- 217.3/351.2 MB 5.7 MB/s eta 0:00:24
   ------------------------ --------------- 218.4/351.2 MB 5.7 MB/s eta 0:00:24
   ------------------------- -------------- 219.7/351.2 MB 5.7 MB/s eta 0:00:23
   ------------------------- -------------- 220.5/351.2 MB 5.7 MB/s eta 0:00:23
   ------------------------- -------------- 221.2/351.2 MB 5.7 MB/s eta 0:00:23
   ------------------------- -------------- 222.0/351.2 MB 5.7 MB/s eta 0:00:23
   ------------------------- -------------- 222.8/351.2 MB 5.7 MB/s eta 0:00:23
   ------------------------- -------------- 223.9/351.2 MB 5.7 MB/s eta 0:00:23
   ------------------------- -------------- 224.1/351.2 MB 5.6 MB/s eta 0:00:23
   ------------------------- -------------- 225.2/351.2 MB 5.6 MB/s eta 0:00:23
   ------------------------- -------------- 225.4/351.2 MB 5.6 MB/s eta 0:00:23
   ------------------------- -------------- 226.5/351.2 MB 5.6 MB/s eta 0:00:23

In [30]:
#### ANN implementation 
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense  # Note: Capital 'D' for Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard # Note: 'o' in TensorBoard

In [33]:
(x_test.shape[1],)

(12,)

In [34]:
## Buld our model
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_test.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])

c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [35]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)

In [41]:
## compile the model
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [45]:
## Setup the Tensorboard
import datetime
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [46]:
## set up early stopping
early_stopping=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [48]:
%pip install tensorboard

Collecting tensorboard
  Downloading tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: absl-py>=0.4 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorboard) (2.4.0)
Requirement already satisfied: grpcio>=1.48.2 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorboard) (1.78.0)
Collecting markdown>=2.6.8 (from tensorboard)
  Downloading markdown-3.10.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: numpy>=1.12.0 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorboard) (2.3.3)
Requirement already satisfied: packaging in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorboard) (25.0)
Requirement already satisfied: pillow in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorboard) (12.0.0)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorboard) (6.33.0)
Requirement already satisfied: setuptools>=41.0.0 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorboard) (80.9.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from tensorboard) (3.1.3)
Requirement already satisfied: typing-extensions~=4.12 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from grpcio>=1.48.2->tensorboard) (4.15.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard) (3.0.3)
Downloading tensorboard-2.20.0-py3-none-any.whl (5.5 MB)
   ---------------------------------------- 0.0/5.5 MB ? eta -:--:--
   --- ------------------------------------ 0.5/5.5 MB 4.0 MB/s eta 0:00:02
   ------------- -------------------------- 1.8/5.5 MB 5.5 MB/s eta 0:00:01
   ------------------ --------------------- 2.6/5.5 MB 5.2 MB/s eta 0:00:01
   -------------------------- ------------- 3.7/5.5 MB 4.7 MB/s eta 0:00:01
   ------------------------------------ --- 5.0/5.5 MB 5.0 MB/s eta 0:00:01
   ---------------------------------------- 5.5/5.5 MB 4.8 MB/s  0:00:01
Downloading tensorboard_data_server-0.7.2-py3-none-any.whl (2.4 kB)
Downloading markdown-3.10.2-py3-none-any.whl (108 kB)
Installing collected packages: tensorboard-data-server, markdown, tensorboard

   ------------- -------------------------- 1/3 [markdown]
   ------------- -------------------------- 1/3 [markdown]
   ------------- -------------------------- 1/3 [markdown]
   ------------- -------------------------- 1/3 [markdown]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   -------------------------- ------------- 2/3 [tensorboard]
   ---------------------------------------- 3/3 [tensorboard]

Successfully installed markdown-3.10.2 tensorboard-2.20.0 tensorboard-data-server-0.7.2
Note: you may need to restart the kernel to use updated packages.

In [49]:
### Train the model
history=model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping]
)

Epoch 1/100

250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8381 - loss: 0.3945 - val_accuracy: 0.8540 - val_loss: 0.3600
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8519 - loss: 0.3589 - val_accuracy: 0.8530 - val_loss: 0.3641
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8574 - loss: 0.3498 - val_accuracy: 0.8615 - val_loss: 0.3489
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8583 - loss: 0.3449 - val_accuracy: 0.8600 - val_loss: 0.3428
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8637 - loss: 0.3403 - val_accuracy: 0.8590 - val_loss: 0.3432
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8622 - loss: 0.3387 - val_accuracy: 0.8630 - val_loss: 0.3539
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8624 - loss: 0.3360 - val_accuracy: 0.8605 - val_loss: 0.3404
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8633 - loss: 0.3336 - val_accuracy: 0.8585 - val_loss: 0.3550
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8655 - loss: 0.3302 - val_accuracy: 0.8570 - val_loss: 0.3572
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8644 - loss: 0.3297 - val_accuracy: 0.8610 - val_loss: 0.3409
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8659 - loss: 0.3275 - val_accuracy: 0.8610 - val_loss: 0.3483
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8680 - loss: 0.3220 - val_accuracy: 0.8580 - val_loss: 0.3439

In [50]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [51]:
### Load ternsorboard extension
%load_ext tensorboard

In [53]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 4380), started 0:00:32 ago. (Use '!kill 4380' to kill it.)