In [2]:
import tensorflow as tf 
from tensorflow.keras.models import load_model
import pickle
import pandas as pd 
import numpy as np

In [4]:
## laod the trained model and pickle and onehot
model = load_model('model.h5')

## To load other files

with open('scaler.pkl','rb') as file:
    scaler= pickle.load(file)

with open('label_encoder.pkl','rb') as file:
    label_enc= pickle.load(file)

with open('oneHot_encoder.pkl','rb') as file:
    onehot=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [28]:
## input_data

data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [29]:
encoded=onehot.transform([[data['Geography']]]).toarray()
df=pd.DataFrame(encoded,columns=onehot.get_feature_names_out(['Geography']))
df

c:\Users\nallapur\.vscode\New folder\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [30]:
data

{'CreditScore': 600,
 'Geography': 'France',
 'Gender': 'Male',
 'Age': 40,
 'Tenure': 3,
 'Balance': 60000,
 'NumOfProducts': 2,
 'HasCrCard': 1,
 'IsActiveMember': 1,
 'EstimatedSalary': 50000}

In [31]:
data=pd.DataFrame([data])

In [35]:
data['Gender']=label_enc.transform(data['Gender'])

In [36]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [37]:
## concat
data=pd.concat([data.drop('Geography',axis=True),df],axis=1)

KeyError: "['Geography'] not found in axis"

In [38]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [39]:
scaled=scaler.transform(data)
scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [41]:
predection = model.predict(scaled)
print(predection)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
[[0.02684078]]